spring:
  profiles:
    active: local
    group:
      local: local_server, common, secret
      blue: blue_server, common, secret

---

spring:
  config:
    activate:
      on-profile: local_server

server:
  port: 8080
react:
  server:
    protocol: http
    host: localhost
    port: 5173

---

spring:
  config:
    activate:
      on-profile: blue_server
server:
  port: 8080
react:
  server:
    protocol: https
    host: ??? ?? ?? ??(ip ?? ???)
    port: 5173

---

spring:
  config:
    activate:
      on-profile: common
  servlet:
    multipart:
      max-file-size: 100MB      # 업로드 가능한 단일 파일 최대 크기
      max-request-size: 1000MB  # 한번의 요청에서 묶음으로 받을 수 있는 최대크기

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations:
    - /mappers/reservation/*.xml
    - /mappers/user/*.xml
    - /mappers/membership/*.xml
    - /mappers/**/*.xml
    - /mappers/register/*.xml
    - /mappers/pay/*.xml
    - /mappers/class/*.xml
    - /mappers/master/*.xml
springdoc:
  override-with-generic-response: false